FROM alpine:3.19

RUN apk add --no-cache \
    wireguard-tools \
    iptables \
    ip6tables \
    iproute2 \
    bash

COPY docker/wg-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

VOLUME /etc/wireguard
EXPOSE 51820/udp

ENTRYPOINT ["/entrypoint.sh"]
